server.tomcat.max-swallow-size=-1

logging.level.org.springframework=DEBUG
logging.level.org.owasp=DEBUG

# Logging Configuration (Logback)
logging.level.org.owasp.esapi=DEBUG
logging.level.root=INFO

# application.properties
spring.config.location=classpath:ESAPI.properties




spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.error.whitelabel.enabled=false
server.error.include-stacktrace=always

server.servlet.context-path=/ProMIS
#server.port=9090

server.name = //

server.servlet.session.timeout=55m
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=true

#spring.mvc.static-path-pattern=/resources/**

spring.thymeleaf.cache=false
logging.level.org.thymeleaf=TRACE

## connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.main.allow-bean-definition-overriding=true
spring.datasource.hikari.connection-timeout=30000 
# Timeout in milliseconds (30 seconds)



# ===============================
# DATABASE CONNECTION
# ===============================
 
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:postgresql://localhost:5432/PromisDB3july
spring.datasource.url=jdbc:postgresql://10.22.1.118:5433/promisdb
#spring.datasource.url=jdbc:postgresql://10.22.1.118:5433/ProMIS29July



spring.datasource.username=postgres
spring.datasource.password=root

 

 
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.tomcat.relaxed-query-chars=|,{,},[,],%
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
# File Upload Configuration

#nEW PROPERTIES
server.tomcat.max-http-form-post-size=200MB

debug = true
file.upload=D:\\file_upload_ProMIS


file.snmsapi1=http://10.22.1.4:8080/SNMS/user1
file.snmsapi=http://10.22.1.4:8080/SNMS


logo.path=http://localhost:8080/SNMS/images/emblem-dark.png
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
file.proMis=http:localhost:8080/ProMIS

pdf.exe = C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe


SERVICE  = ProMIS
HMAC_URL = http://localhost:8085/hmac
ENCR_URL =  http://localhost:8085/encryption
HANDSHAKING_URL = http://localhost:8085/handshake
DEC_URL =http://localhost:8085/decryption
LOGOUT_URL = http://localhost:8085/logoutAll
Token_validate = http://localhost:8085/isTokenValid
SESS_TIMEOUT = http://localhost:8085/timeout
PARICHAY_URL=https://parichay.staging.nic.in
server.port 8080