
# ===============================
# LOGGING (CRITICAL)
# ===============================
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.owasp=WARN
logging.level.org.owasp.esapi=WARN




# ===============================
# HIKARI POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB


server.tomcat.max-swallow-size=-1
# application.properties
spring.config.location=classpath:ESAPI.properties

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.error.whitelabel.enabled=false
server.error.include-stacktrace=never


server.servlet.context-path=/ProMIS
server.port=80

server.name = /sfioprosecution.nic.in/

server.servlet.session.timeout=40m

spring.thymeleaf.cache=true




spring.main.allow-bean-definition-overriding=true




# ===============================
# DATABASE CONNECTION
# ===============================
 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.153.169.243:5432/prosecution5march2025
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

 
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
 

server.tomcat.relaxed-query-chars=|,{,},[,],%

file.upload=/usr/local/file_upload_ProMIS

#file.snmsapi1=http://10.22.1.118:8080/SNMS/user1
#file.snmsapi=http://10.22.1.118:8080/SNMS


logo.path=http://sfioprosecution/Prosecution/images/emblem-dark.png
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
file.proMis=http://sfioprosecution/Prosecution

#pdf.exe = C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe



SERVICE  = ProMIS
HMAC_URL = http://localhost:8085/hmac
ENCR_URL =  http://localhost:8085/encryption
HANDSHAKING_URL = http://localhost:8085/handshake
DEC_URL =http://localhost:8085/decryption
LOGOUT_URL = http://localhost:8085/logoutAll
Token_validate = http://localhost:8085/isTokenValid
SESS_TIMEOUT = http://localhost:8085/timeout
PARICHAY_URL=https://parichay.staging.nic.in
